### ISSUE TITLE
TypeError: Cannot read property 'MsTokenUrl' of undefined

### ISSUE THREAD

**Issue by arielelkin** [himate/himate#99]
1. clone repository
1. add `settings.json` file
1. `./tools/start-all-apps.sh`
1. `./tools/stop-all-apps.sh`
1. `cd apps/customers`
1. `meteor run ios`, output below:

```
$ meteor run ios
[[[[[ ~/_PROGRESS/himate/apps/customers ]]]]] 

=> Started proxy.                             
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
=> Started MongoDB.                           
                                                                                   
WARNING: It looks like you are using OAuth2 login in your app. Meteor's OAuth2 implementation does not currently work
         with mobile apps in local development mode, except in the iOS simulator. You can run the iOS simulator with
         'meteor run ios'. For additional workarounds, see
         https://github.com/meteor/meteor/wiki/OAuth-for-mobile-Meteor-clients.
W20160606-16:38:20.124(2)? (STDERR)           
W20160606-16:38:20.126(2)? (STDERR) /Users/arielelkin/.meteor/packages/meteor-tool/.1.1.10.1birssi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160606-16:38:20.126(2)? (STDERR)             				throw(ex);
W20160606-16:38:20.126(2)? (STDERR)             				      ^
W20160606-16:38:20.126(2)? (STDERR) TypeError: Cannot read property 'MsTokenUrl' of undefined
W20160606-16:38:20.126(2)? (STDERR)     at Meteor.methods.categories_add.check.title.de (server/methods/campaign_translate.js:5:43)
W20160606-16:38:20.126(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/packages/himate_base.js:1252:4
W20160606-16:38:20.126(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/packages/himate_base.js:1615:3
W20160606-16:38:20.127(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/boot.js:242:10
W20160606-16:38:20.127(2)? (STDERR)     at Array.forEach (native)
W20160606-16:38:20.127(2)? (STDERR)     at Function._.each._.forEach (/Users/arielelkin/.meteor/packages/meteor-tool/.1.1.10.1birssi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160606-16:38:20.127(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/boot.js:137:5
=> Started app on iOS Simulator.              
=> Exited with code: 8                        
W20160606-16:38:52.489(2)? (STDERR)           
W20160606-16:38:52.490(2)? (STDERR) /Users/arielelkin/.meteor/packages/meteor-tool/.1.1.10.1birssi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160606-16:38:52.490(2)? (STDERR) 						throw(ex);
W20160606-16:38:52.491(2)? (STDERR) 						      ^
W20160606-16:38:52.542(2)? (STDERR) TypeError: Cannot read property 'MsTokenUrl' of undefined
W20160606-16:38:52.542(2)? (STDERR)     at Meteor.methods.categories_add.check.title.de (server/methods/campaign_translate.js:5:43)
W20160606-16:38:52.542(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/packages/himate_base.js:1252:4
W20160606-16:38:52.542(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/packages/himate_base.js:1615:3
W20160606-16:38:52.542(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/boot.js:242:10
W20160606-16:38:52.542(2)? (STDERR)     at Array.forEach (native)
W20160606-16:38:52.542(2)? (STDERR)     at Function._.each._.forEach (/Users/arielelkin/.meteor/packages/meteor-tool/.1.1.10.1birssi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160606-16:38:52.542(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
W20160606-16:39:06.218(2)? (STDERR)           
W20160606-16:39:06.219(2)? (STDERR) /Users/arielelkin/.meteor/packages/meteor-tool/.1.1.10.1birssi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160606-16:39:06.219(2)? (STDERR) 						throw(ex);
W20160606-16:39:06.219(2)? (STDERR) 						      ^
W20160606-16:39:06.270(2)? (STDERR) TypeError: Cannot read property 'MsTokenUrl' of undefined
W20160606-16:39:06.270(2)? (STDERR)     at Meteor.methods.categories_add.check.title.de (server/methods/campaign_translate.js:5:43)
W20160606-16:39:06.271(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/packages/himate_base.js:1252:4
W20160606-16:39:06.271(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/packages/himate_base.js:1615:3
W20160606-16:39:06.271(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/boot.js:242:10
W20160606-16:39:06.271(2)? (STDERR)     at Array.forEach (native)
W20160606-16:39:06.271(2)? (STDERR)     at Function._.each._.forEach (/Users/arielelkin/.meteor/packages/meteor-tool/.1.1.10.1birssi++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160606-16:39:06.271(2)? (STDERR)     at /Users/arielelkin/_PROGRESS/himate/apps/customers/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
```

Any thoughts?

**Comment by fishi0x01** [comment]
Is the `translation.MsTokenUrl` property set inside your `settings.json`?

Just in case can you please confirm that your `settings.json` looks something like the following:
```
{
    "translation": {
        "MsTokenUrl": "%YOURTOKENURL%",
        "MsClientId": "%YOURCLIENTID%",
        "MsClientSecret": "%YOURSECRET%",
        "MsTokenScope": "http://api.microsofttranslator.com",
        "MsTokenGrantType": "client_credentials",
        "MsTranslatorUrl": "http://api.microsofttranslator.com/v2/Http.svc/Translate"
    },

    "mandrill": {
        "smtp": {
            "server": "%YOURSMTPSERVER%",
            "port": "%YOURSMTPSERVERPORT%"
        },
        "username": "%YOURUSERNAME%",
        "apiKey": "%YOURAPIKEY%"
    },

    "contacts": {
        "noreply": "%YOURNOREPLAYADRESS%"
    }
}
```

**Comment by arielelkin** [comment]
yes, `translation.MSTokenUrl` is set.

i've sent you a copy of my `settings.json`

**Comment by simondeichsel** [comment]
it's fixed
